### ISSUE TITLE
Comparison between DataSketches, DDSketch, t-digests et al.

### ISSUE THREAD

**Issue by breandan** [apache/datasketches-java#357]
I see [DataSketches](https://github.com/apache/datasketches-java/blob/master/src/main/java/org/apache/datasketches/quantiles/DoublesSketch.java) and [DDSketch](https://github.com/DataDog/sketches-java/blob/master/src/main/java/com/datadoghq/sketch/QuantileSketch.java) both offer a floating-point quantile-based sketch based on Agarwal et al.'s [Mergeable summaries](https://www.cs.utah.edu/~jeffp/papers/merge-summ.pdf). I also noticed that DataSketches maintains an [extensive test suite](https://github.com/apache/datasketches-characterization) for benchmarking purposes. It would be nice to see a performance comparison between these two mergeable quantile sketching implementations, as their interfaces (at least at first glance) appear to be quite similar. Or are there any significant differences I might have overlooked? Thank you!

cc: @CharlesMasson @richardstartin

**Comment by AlexanderSaydakov** [comment]
You seem to suggest that the sketches are based on the same algorithm, but it is not the case. The algorithm is not even similar, the definition of error is different too, and I don't see much similarity in the API. For instance, DDSketch has a method to get a value given a rank (quantile), but not the other way around.
The DataSketches DoublesSketch is a specialized implementation for primitive double values, but the algorithm does not assume numeric input. There is a generic implementation for arbitrary types. Besides, we have a better algorithm now. See the KLL sketch. It has a specialized implementation for float values, and no generic implementation (in Java, yet). Also for relative error we have the REQ sketch. Perhaps, it might be possible to do some comparison, but it is even hard to decide which ones are closer in functionality.

**Comment by jmalkin** [comment]
Briefly skimming the DD Sketch paper, I agree with @AlexanderSaydakov that it's definitely not based on the Mergeable Summaries paper. But that's also not the rank-error quantiles sketch we recommend at this point: KLL provides superior performance at a smaller sketch size.

Based on the error guarantees, it seems like our REQ (Relative Error Quantiles) sketch is a more appropriate comparison. But there are enough differences to make that comparison not entirely straightforward.

DDSketch is defined only for strictly positive values: REQ is defined over any arbitrary domain. You can use 2 DDSketches to handle negatives, but that still seems to exclude 0, which can be a non-trivial portion of probability mass for some queries.

REQ has high accuracy on either the high or low end, and is fully symmetric in performance if you switch between them. Looking at the binning approach of DDSketch, (and I could be wrong here) I think its accuracy guarantee is only what we'd count as high-end accuracy. (Log transform + a second sketch for negative values, etc, perhaps?)

DDSketch's bucketing approach allows for deletions, which REQ does not.

And I believe REQ provides a significantly wider range of possible queries.

There are ultimately enough differences that finding a comparison that doesn't play to the strengths of one based on a specific problem structure is itself something of a challenge.

**Comment by breandan** [comment]
> You seem to suggest that the sketches are based on the same algorithm

I did not suggest this, both the [DDSketch authors](http://www.vldb.org/pvldb/vol12/p2195-masson.pdf) and your collaborator @leerho [directly cite](https://github.com/apache/datasketches-java/blob/27ecce938555d731f29df97f12f4744a0efb663d/src/main/java/org/apache/datasketches/quantiles/DoublesSketch.java#L117-L120) Agarwal et al. (2012):

```
 * <p>This is an implementation of the Low Discrepancy Mergeable Quantiles Sketch, using double
 * values, described in section 3.2 of the journal version of the paper "Mergeable Summaries"
 * by Agarwal, Cormode, Huang, Phillips, Wei, and Yi.
 * <a href="http://dblp.org/rec/html/journals/tods/AgarwalCHPWY13"></a></p>
```

My high-level understanding is that both provide a mergeable quantile sketch over some sequence, and would be interested in understanding their tradeoffs. If I am misinformed and this is not the case, please feel free to ignore or close this ticket. Thanks!

**Comment by PavelVesely** [comment]
The fact that DDSketch paper cites the Agarwal et al. paper doesn't mean that DDSketch is based on the ideas from the Agarwal et al. paper. As far as I know, it is quite different.

As mentioned above, the major difference between DDSketch and KLL/ReqSketch is indeed in the guarantee offered. For DDSketch, the guarantee is in the value space, that is, the *value* of the estimated quantile y returned by the sketch is by at most epsilon * x different from the true quantile x. On the other hand, KLL/ReqSketch offer guarantee in the rank space, that is, on quantile query q, they return an input item with rank close to q. The difference between these two guarantees is explained for instance in Section 2.1 in [this paper](https://arxiv.org/abs/2102.09299).

**Comment by jmalkin** [comment]
Ah, thanks, @PavelVesely -- I missed the relative rank vs relative value part.

But that reinforces my take that it's not trivial to do a fair comparison since they're such different sketches.

**Comment by AlexanderSaydakov** [comment]
> My high-level understanding is that both provide a mergeable quantile sketch over some sequence

Yes, on a high level they are mergeable quantile sketches. It might be interesting to compare the performance if we can agree which sketches to compare and what parameters we can set so that something is held approximately equivalent. For example, if it would be possible to make the serialized size about the same, we can compare accuracy and update time. Or, set the accuracy to about the same (is it possible at all given the different definitions?), and see which one is smaller or faster, and so on.

**Comment by breandan** [comment]
Got it, thanks very much for clarifying! I am becoming more familiar with the sketching literature and appreciate your helpful remarks. Evaluation-wise, that does seem difficult to do a fair comparison between rank-space and value-space. Perhaps a better target would be @tdunning's [t-digests](https://github.com/tdunning/t-digest), who appears to show competitive results on [relative error](https://github.com/tdunning/t-digest/blob/8630c2b678ae5d2c055ee26bea6cf0af79c55fa6/quality/kll-comparison.pdf) with respect to KLL sketch. It would be interesting to see if those results withstood a clean-room test, or what other metrics you would use.

More importantly, for those who are less familiar with the evaluation methods and SoTA in your area of research, it would be helpful to see a flowchart or feature comparison matrix to understand the tradeoffs between various sketching algorithms. For my own use case, I am interested in computing multidimensional statistics (e.g. covariance, copula, mutual information) on multisets whose elements share multiple categorical attributes. Any further insights you could provide would be welcome.

**Comment by leerho** [comment]
Our classic QuantilesSketch *is* a faithful derivation of one of the
Agarwal, et al (2012) paper's algorithms.  Although the DDSketch authors
cite the Agarwal paper, it doesn't mean that what they implemented
resembles Agarwal at all.  It is a totally different algorithm with very
different trade-offs as is discussed above.

This doesn't mean that a reasonable, detailed characterization study
comparing, for example, the DDSketch vs the REQSketch wouldn't be a useful
thing to have.  It is just that we haven't had the time to do it.  If this
is something that you would consider doing and contributing, we would
gladly consider adding it to our website documentation.

Cheers,

Lee.

**Comment by tdunning** [comment]
Frankly, a comparison of comparison methods is nearly as educational as a
comparison between algorithms.

Issues come out all over the place:

- Are you interested in quantile errors or measurement space errors?

- What is of interest? Average, maximum or the distribution of errors? Or
errors at particular quantiles?

- What data? What distribution? What scale?

- Many algorithms keep all data up to some point. What is that point? What
happens in the transition to summarization? Which points are combined /
summarized first?

- Are some quantiles more interesting than others?

- Is it ok if larger errors are made, but rarely? Or for measurements
deemed "less interesting"?

- Is accuracy different if lots of sketches are merged?

- If you are interested in particular quantiles (0.1%, 99.9%, 90%) is there
a special behavior when your data set is or is not evenly divisible by that
residual? For instance, in computing the 99th percentile of 10,000, is that
interesting different from computing the 99th percentile of 10,001 or
10,037?

**Comment by breandan** [comment]
I share your frustration and am beginning to appreciate the difficulty of conducting a fair comparison: on one hand, these sketches are built with different guarantees in mind (e.g. relative error or rank error), and a single metric may not accurately capture the benefits they provide (e.g. latency, memory) or data types they support (e.g. categorical, ordinal, numerical).

On the other hand, we may be splitting hairs a little. You have a mergeable summary of some probability space. If we choose,

1.  a fixed data type (e.g. ordinal)
2. a fixed hardware (e.g. 8-cores, merged)
3. a fixed probability metric (e.g. Kolmogorov–Smirnov, Kantorovich-Rubenstein, Lévy–Prokhorov)
4. a set of performance criteria (e.g. latency, memory, precision) 

and compare the sketch with an exact summary - then rinse and repeat for each algorithm (LDMQS, REQ/KLL, DDSketch, t-digest et al.), and report the pareto efficiency across all performance criteria - does that seem reasonable?

**Comment by jmalkin** [comment]
Thanks for the specific questions, @tdunning . Those are the sorts of things I was sweeping up with the generic comment about it being a challenging task to do a fair comparison.

(And yes, we're aware we need to redo the KLL vs t-digest page -- really should just pull it for now -- to include a wider variety of tests and context around which sorts of queries play to the strengths of the different sketches. In other words, more discussion of exactly the sorts of things you mentioned here.)

**Comment by tdunning** [comment]
breandan,

That is a good start. Additional issues I have had to deal with just in
building tests for t-digest (much less comparing different sketches):

- extremely skewed data can do funny things. I use uniform, normal,
log-normal and Gamma(0.1, 0.1) for most testing.

- repeated data points can mess things up. This is one of the hardest
points to deal with because assumptions about continuous distributions or
distinct values creep in all the time.

- the number of samples matters a bunch. There are different pathologies
that turn up with small, medium and large scale data.

- focusing on particular quantiles or quantile ranges can be important

- data order may matter

- accuracy and performance may be different for a sketch that has done a
round-trip through serialization

IN my experience, presenting all of these tests overloads people evaluating
a sketch, but omitting any of these issues is not reasonable if you are
choosing a sketch for production use.

The simplicity of the failure modes is actually an interesting feature. For
instance, for HdrHistogram (or my version, the LogHistogram), extremely
skewed data doesn't matter. You get accuracy in measurement space and that
totally ruins some quantile information on some distributions. Same answer
for repeated data. Same answer for differing amounts of data. Data order
doesn't matter and accuracy is unaffected by serialization. On the other
hand, simple answers to these questions also means that you have a sketch
that is completely unusable for many applications even if it is fantastic
for some.

**Comment by leerho** [comment]
This issue has not had any further comments for almost 2 years. So I think we can close this issue.  It can be reopened at any time.
