### ISSUE TITLE
Test Smell: It is not a good test practice to introduce nondeterministic randomness in test code

### ISSUE THREAD

**Issue by TestSmell** [apache/datasketches-java#413]
Hi!

We notice that the random number generator (RNG) is used to produce test code in your project.
For example, a random generator in the test method named ''checkKomologorovSmirnovStatistic1() '' in ''KolmogorovSmirnovTest.java''
<img width="547" alt="截屏2022-08-17 下午7 04 14" src="https://user-images.githubusercontent.com/110402847/185103732-4bec8197-d68f-4460-9a28-480d56c6b293.png">

But generating random data in test code is not a good test practice. Since Using nondeterministic randomized data may lead to unexpected unit test failure and once the test case fails, it is hard to trace what test data causes it.

Solution:
There are two solutions:
set a random seed number for your random generator
using a hash method to generate random data

**Comment by leerho** [comment]
I agree. Will fix.

**Comment by leerho** [comment]
Done.
