### ISSUE TITLE
Is the serialized data compatible between different versions?

### ISSUE THREAD

**Issue by lukoou3** [apache/datasketches-java#454]
Is the serialized data compatible between different versions?

can datasketches deserialize data serialized by other versions?

**Comment by AlexanderSaydakov** [comment]
The library can deserialize data serialized by older versions of the library.
Also there is compatibility between implementations of the library in Java and C++ (and Python, which is a thin wrapper around C++) for most sketches.

**Comment by leerho** [comment]
I think this question has been addressed.  So I'll close this issue.
If you have any further questions you can reopen this issue.
