### ISSUE TITLE
Level-0 sorting for `KllItemsSketch<T>` is not based on `Comparator<T>`

### ISSUE THREAD

**Issue by fanyang01** [apache/datasketches-java#527]
https://github.com/apache/datasketches-java/blob/8ae234b13c852003bd35aa57ebb1e63d189bc52a/src/main/java/org/apache/datasketches/kll/KllItemsHelper.java#L436-L438

The `Arrays.sort` API in the above code

> sorts the specified range of the specified array of objects into ascending order, according to the [natural ordering](https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html) of its elements. ... All elements in this range must implement the [Comparable](https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html) interface`.

It appears that `Arrays.sort(inBuf, adjBeg, adjBeg + adjPop, comp)` should be called instead.

**Comment by leerho** [comment]
Thank you! 
This was a bit subtle.   It only occurs during merge, when a compaction is required, and when the object T cannot be naturally ordered. 
Will fix this and add a test for it.

**Comment by jmalkin** [comment]
This has been merged into the main branch (next release with this still TBD). It was also back-ported into the 5.0.X branch, and I'm working on starting a release vote for a v5.0.2 right now, which will include this fix.
