### ISSUE TITLE
Bug in datasketches-java 6.0.0

### ISSUE THREAD

**Issue by leerho** [apache/datasketches-java#568]
The function in /theta/Sketch::getCompactSketchMaxBytes(lgNomEntries) is computed incorrectly due to a misplaced right-parentheses. Ironically the test method that tests this function made the same mistake!  

This function is also referenced by /theta/Sketches/ with the same name.

The Javadocs in both places are also incorrect.

**Comment by AlexanderSaydakov** [comment]
I would suggest to test not by asserting a particular number, but by measuring the actual peak size.
https://github.com/apache/datasketches-cpp/blob/76edd74f5db286b672c170a8ded4ce39b3a8800f/theta/test/theta_sketch_test.cpp#L561

**Comment by leerho** [comment]
:)

**Comment by leerho** [comment]
Fixed in release 6.1.0.
